trigger:
- main

jobs:
- job: Build_and_deploy
  pool:
    vmImage: windows-latest

  variables:
  - name: tagRelease
    value: tagTest

  steps:
   - template: azure-pipelines-build.yml
   - script: |
       npm run publish -- url:http://82.223.97.22:3000/deploy/web secret:$(khanonjs-deployer-secret)
     displayName: 'Publish web'


